import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";
import { typography } from "@/constants/typography";

/** Merged from the part files that used to sit beside this one: they were
 *  split only to satisfy a 150-line cap, and re-spread here at runtime. */
export const styles = StyleSheet.create({

  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  headerGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 350,
  },
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingTop: 10,
    gap: 16,
  },
  loadingCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 28,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    marginTop: 20,
  },
  emptyText: {
    fontWeight: "500",
    color: Colors.textMuted,
  },
  header: {
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 2,
  },
  avatarWrap: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: Colors.brandSkin,
    borderWidth: 3,
    borderColor: Colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  avatarImage: {
    width: 84,
    height: 84,
    borderRadius: 42,
  },
  avatarText: {
    fontWeight: "700",
    fontSize: typography.sizes.extraLarge,
    color: Colors.primary,
  },
  onlineDot: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.success,
    borderWidth: 2,
    borderColor: Colors.white,
  },
  name: {
    fontWeight: "700",
    fontSize: typography.sizes.extraLarge,
    color: Colors.text,
    marginBottom: 4,
  },
  memberSince: {
    fontWeight: "500",
    fontSize: typography.sizes.medium,
    color: Colors.textSecondary,
  },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.brand,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    marginTop: 10,
  },
  ratingText: {
    fontWeight: "700",
    fontSize: typography.sizes.medium,
    color: Colors.white,
  },
  statsCard: {
    flexDirection: "row",
    backgroundColor: Colors.white,
    borderRadius: 16,
    paddingVertical: 20,
    marginTop: 8,
    shadowColor: "rgba(0,0,0,0.05)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  statCol: {
    flex: 1,
    alignItems: "center",
  },
  statDivider: {
    width: 1,
    backgroundColor: Colors.border,
  },
  statValueBold: {
    fontWeight: "700",
    fontSize: typography.sizes.large,
    color: Colors.text,
    marginBottom: 4,
  },
  statLabelMuted: {
    fontWeight: "500",
    fontSize: typography.sizes.small,
    color: Colors.textMuted,
  },
  docsRow: {
    flexDirection: "row",
    gap: 12,
  },

  docCard: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  docIconWrap: {
    marginBottom: 10,
  },
  docTitle: {
    fontWeight: "600",
    fontSize: typography.sizes.medium,
    color: Colors.text,
    textAlign: "center",
    marginBottom: 12,
  },
  statusPill: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusPillText: {
    fontWeight: "700",
    fontSize: typography.sizes.small,
  },
  currentVehicleCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.white,
    padding: 16,
    borderRadius: 16,
    shadowColor: "rgba(0,0,0,0.03)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  vehicleIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.surfaceContainer,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  vehicleCopy: {
    flex: 1,
  },
  vehicleTitleSmall: {
    fontWeight: "500",
    fontSize: typography.sizes.small,
    color: Colors.textMuted,
    marginBottom: 4,
  },
  vehicleValue: {
    fontWeight: "600",
    fontSize: typography.sizes.medium,
    color: Colors.text,
  },
  sectionHeader: {
    fontWeight: "700",
    fontSize: typography.sizes.large,
    color: Colors.text,
    marginTop: 8,
    marginBottom: -4,
  },
  menuList: {
    gap: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
  },
  menuIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.brandSkin,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  menuCopy: {
    flex: 1,
  },
  menuLabel: {
    fontWeight: "600",
    fontSize: typography.sizes.medium,
    color: Colors.text,
    marginBottom: 4,
  },
  menuSubtitle: {
    fontWeight: "500",
    fontSize: typography.sizes.small,
    color: Colors.textMuted,
  },
  signOutButtonWrap: {
    marginTop: 16,
    borderRadius: 16,
    overflow: "hidden",
  },
  signOutGradient: {
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  signOutText: {
    fontWeight: "700",
    fontSize: typography.sizes.large,
    color: Colors.white,
  },
  devButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 8,
  },
  devBadge: {
    fontWeight: "700",
    fontSize: typography.sizes.small,
    color: Colors.surface,
    backgroundColor: Colors.textMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },
  devButtonText: {
    fontWeight: "500",
    fontSize: typography.sizes.medium,
    color: Colors.textMuted,
    textDecorationLine: "underline",
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  modalCard: {
    maxHeight: "85%",
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 30,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  modalTitle: {
    fontWeight: "700",
    fontSize: typography.sizes.large,
    color: Colors.text,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  modalScroll: {
    paddingHorizontal: 16,
  },
  modalScrollContent: {
    paddingBottom: 24,
  },
});

export const modalStyles = StyleSheet.create({

  fieldLabel: {
    fontWeight: "600",
    fontSize: typography.sizes.medium,
    color: Colors.text,
    marginBottom: 6,
  },
  formWrap: {
    paddingVertical: 8,
    gap: 4,
  },
  genderRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  genderOption: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  genderOptionActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  genderText: {
    fontWeight: "600",
    fontSize: typography.sizes.medium,
    color: Colors.textMuted,
  },
  genderTextActive: {
    color: Colors.white,
  },

  docActions: {
    gap: 10,
    marginTop: 12,
  },
  infoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 14,
    marginTop: 12,
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: 12,
  },
  infoText: {
    flex: 1,
    fontWeight: "400",
    fontSize: typography.sizes.medium,
    color: Colors.textMuted,
    lineHeight: typography.lineHeights.medium,
  },
  bankList: {
    marginTop: 12,
  },
  bankListTitle: {
    fontWeight: "600",
    fontSize: typography.sizes.medium,
    color: Colors.text,
    marginBottom: 8,
  },
  bankItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: 10,
    marginBottom: 8,
  },
  bankItemDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  bankItemCopy: {
    flex: 1,
  },
  bankItemNumber: {
    fontWeight: "600",
    fontSize: typography.sizes.medium,
    color: Colors.text,
  },
  bankItemIfsc: {
    fontWeight: "400",
    fontSize: typography.sizes.small,
    color: Colors.textMuted,
    marginTop: 2,
  },

  defaultBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: Colors.primaryLight,
  },
  defaultBadgeText: {
    fontWeight: "600",
    fontSize: typography.sizes.small,
    color: Colors.primary,
  },
  bankFormWrap: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  bankFormTitle: {
    fontWeight: "700",
    fontSize: typography.sizes.medium,
    color: Colors.text,
    marginBottom: 12,
  },
  passwordForm: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  supportBox: {
    alignItems: "center",
    gap: 8,
    padding: 20,
    marginTop: 12,
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: 12,
  },
  supportTitle: {
    fontWeight: "700",
    fontSize: typography.sizes.large,
    color: Colors.text,
  },
  supportText: {
    fontWeight: "400",
    fontSize: typography.sizes.medium,
    color: Colors.textMuted,
    textAlign: "center",
    lineHeight: typography.lineHeights.medium,
  },
});
