import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";
import { typography } from "@/constants/typography";

// Styles for ScheduleDateTimeSheet.tsx, moved out so the component file stays under 150 lines.
// Values are unchanged.

export const createStyles = (colors: typeof Colors.light, primary: string) =>
  StyleSheet.create({
    overlay: { flex: 1, justifyContent: "flex-end" },
    scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(15, 23, 42, 0.68)" },
    sheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 26,
      borderTopRightRadius: 26,
      paddingTop: 16,
      paddingHorizontal: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 16,
    },
    handle: {
      alignSelf: "center",
      width: 46,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: 16,
    },
    title: { fontSize: typography.sizes.large, fontWeight: "800", color: colors.text, marginBottom: 4 },
    subtitle: { fontSize: typography.sizes.medium, color: colors.textSecondary, marginBottom: 16, fontWeight: "500" },
    previewCard: {
      backgroundColor: colors.surfaceSecondary,
      borderRadius: 14,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
      gap: 4,
    },
    previewLabel: { fontSize: typography.sizes.small, fontWeight: "800", color: colors.textSecondary, letterSpacing: 0.5 },
    previewValue: { fontSize: typography.sizes.large, fontWeight: "800", color: colors.text },
    sectionLabel: {
      fontSize: typography.sizes.medium,
      fontWeight: "700",
      color: colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 8,
      marginTop: 4,
    },
    datesContainer: { marginBottom: 12 },
    datesContent: { gap: 10, paddingRight: 20 },
    dateCard: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      minWidth: 84,
      borderWidth: 1.5,
      borderColor: "transparent",
    },
    dateCardActive: {
      backgroundColor: `${primary}15`,
      borderColor: primary,
    },
    dateDayText: { fontSize: typography.sizes.small, fontWeight: "600", color: colors.textSecondary, marginBottom: 2 },
    dateDayTextActive: { color: primary, fontWeight: "700" },
    dateValText: { fontSize: typography.sizes.medium, fontWeight: "700", color: colors.text },
    dateValTextActive: { color: primary },
    timeRow: { gap: 8, paddingBottom: 12 },
    timeChip: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 20,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: "transparent",
    },
    timeChipActive: {
      backgroundColor: `${primary}15`,
      borderColor: primary,
    },
    timeChipText: { fontSize: typography.sizes.medium, fontWeight: "700", color: colors.text },
    timeChipTextActive: { color: primary },
    ampmRow: { flexDirection: "row", gap: 12, marginBottom: 16 },
    ampmBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      borderWidth: 1.5,
      borderColor: "transparent",
    },
    ampmBtnActive: {
      backgroundColor: `${primary}15`,
      borderColor: primary,
    },
    ampmBtnText: { fontSize: typography.sizes.medium, fontWeight: "700", color: colors.text },
    ampmBtnTextActive: { color: primary },
    confirmBtn: {
      backgroundColor: primary,
      paddingVertical: 15,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 52,
    },
    confirmBtnDisabled: { opacity: 0.6 },
    confirmBtnText: { color: "#fff", fontSize: typography.sizes.large, fontWeight: "800" },
  });
