import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";
import { moderateScale } from "react-native-size-matters";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  inner: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: "center",
    gap: 24,
  },
  logoSection: {
    alignItems: "center",
    gap: 6,
  },
  logoContainer: {
    width: moderateScale(72),
    height: moderateScale(72),
    borderRadius: moderateScale(22),
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  appName: {
    fontSize: moderateScale(26),
    fontWeight: "800",
    color: Colors.text,
    letterSpacing: -0.5,
  },
  tagline: {
    fontSize: moderateScale(14),
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  formSection: {
    gap: 14,
  },
  countryCodeGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  formTitle: {
    fontSize: moderateScale(22),
    fontWeight: "700",
    color: Colors.text,
  },
  formSubtitle: {
    fontSize: moderateScale(14),
    color: Colors.textSecondary,
    lineHeight: 20,
    marginTop: -6,
  },
  demoHint: {
    fontSize: moderateScale(13),
    color: Colors.primary,
    backgroundColor: Colors.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: moderateScale(8),
    alignSelf: "flex-start",
    fontWeight: "500",
  },
  tabRow: {
    flexDirection: "row",
    backgroundColor: Colors.surfaceAlt,
    borderRadius: moderateScale(10),
    padding: 3,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: moderateScale(8),
    alignItems: "center",
  },
  tabActive: {
    backgroundColor: Colors.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  tabText: {
    fontSize: moderateScale(14),
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  tabTextActive: {
    color: Colors.primary,
  },
  inputGroup: {
    gap: 5,
  },
  inputLabel: {
    fontSize: moderateScale(13),
    fontWeight: "600",
    color: Colors.text,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: moderateScale(12),
    paddingHorizontal: 14,
    height: moderateScale(48),
    gap: 10,
    backgroundColor: Colors.surface,
  },
  countryCode: {
    fontSize: moderateScale(16),
    fontWeight: "600",
    color: Colors.text,
  },
  phoneDivider: {
    width: 1,
    height: 24,
    backgroundColor: Colors.border,
  },
  input: {
    flex: 1,
    fontSize: moderateScale(16),
    color: Colors.text,
  },
  primaryButton: {
    height: moderateScale(50),
    borderRadius: moderateScale(25),
    backgroundColor: Colors.primary,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    marginTop: 4,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: Colors.white,
    fontSize: moderateScale(16),
    fontWeight: "700",
  },
  otpContainer: {
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginVertical: 4,
  },
  otpBox: {
    width: moderateScale(44),
    height: moderateScale(50),
    borderRadius: moderateScale(10),
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    textAlign: "center",
    fontSize: moderateScale(20),
    fontWeight: "700",
    color: Colors.text,
  },
  otpBoxFilled: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryLight,
  },
  backButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: Colors.surfaceAlt,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  resendButton: {
    alignItems: "center",
    paddingVertical: 12,
  },
  resendText: {
    fontSize: moderateScale(15),
    color: Colors.primary,
    fontWeight: "600",
  },
  switchButton: {
    alignItems: "center",
    paddingVertical: 2,
  },
  switchText: {
    fontSize: moderateScale(14),
    color: Colors.textSecondary,
    fontWeight: "500",
  },
});
