import { Dimensions, StyleSheet } from "react-native";
import { moderateScale } from "react-native-size-matters";
import { Colors } from "@/constants/colors";
import { typography } from "@/constants/typography";

const { height } = Dimensions.get("window");

/** Merged from the part files that used to sit beside this one: they were
 *  split only to satisfy a 150-line cap, and re-spread here at runtime. */
export const styles = StyleSheet.create({

  sosBtn: {
    backgroundColor: Colors.error,
    borderRadius: 16,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  navArrowMarker: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.brand,
    borderWidth: 2,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  container: { flex: 1, backgroundColor: Colors.background },
  keyboardAvoider: { flex: 1 },
  cardScroll: {
    flex: 1,
  },
  cardScrollContent: {
    flexGrow: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderColor: Colors.border,
    zIndex: 10,
  },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: typography.sizes.large, fontWeight: "700", color: Colors.text },
  mapContainer: { flex: 1 },
  userMarkerWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
  },
  userMarkerBadge: {
    backgroundColor: Colors.success,
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: Colors.white,
    elevation: 4,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  redMarkerDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: Colors.error,
    borderWidth: 2,
    borderColor: Colors.white,
    elevation: 4,
  },
  bottomCard: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: moderateScale(24),
    borderTopRightRadius: moderateScale(24),
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 20,
    marginTop: -20,
    maxHeight: height * 0.58,
    paddingTop: 18,
    paddingHorizontal: 20,
  },

  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  orderLabel: {
    fontSize: typography.sizes.medium,
    fontWeight: "700",
    color: Colors.textSecondary,
  },
  stepContainer: {
    flex: 1,
    justifyContent: "space-between",
    paddingBottom: 4,
    gap: 16,
  },
  stepTitle: {
    fontSize: typography.sizes.large,
    fontWeight: "800",
    color: Colors.text,
    marginBottom: 12,
  },
  stepTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  stepTitleInRow: {
    flex: 1,
    marginBottom: 0,
  },
  stepHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },

  pulseDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.success,
  },
  infoBox: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 12,
    marginBottom: 16,
  },
  infoItem: {
    paddingVertical: 4,
  },
  infoLabel: {
    fontSize: typography.sizes.small,
    fontWeight: "700",
    color: Colors.textMuted,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  infoText: {
    fontSize: typography.sizes.medium,
    fontWeight: "700",
    color: Colors.text,
  },
  subText: {
    fontSize: typography.sizes.small,
    color: Colors.textSecondary,
    marginTop: 1,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.border,
    marginVertical: 10,
  },
  actionBtn: {
    backgroundColor: Colors.brand,
    paddingVertical: 15,
    borderRadius: moderateScale(12),
    alignItems: "center",
    elevation: 3,
  },
  actionBtnText: {
    color: Colors.white,
    fontSize: typography.sizes.medium,
    fontWeight: "800",
  },
  simPanel: {
    backgroundColor: Colors.text,
    borderRadius: moderateScale(12),
    padding: 12,
    marginBottom: 14,
  },
  simStatsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  simStatItem: {
    alignItems: "center",
    width: "30%",
  },
  simStatLabel: {
    fontSize: typography.sizes.small,
    fontWeight: "700",
    color: Colors.textMuted,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  simStatValue: {
    fontSize: typography.sizes.medium,
    fontWeight: "800",
    color: Colors.white,
  },
  simToggleBtn: {
    backgroundColor: Colors.text,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: moderateScale(8),
    gap: 8,
  },
  simToggleBtnActive: {
    backgroundColor: Colors.error,
  },
  simToggleText: {
    color: Colors.white,
    fontSize: typography.sizes.medium,
    fontWeight: "700",
  },
  restaurantName: {
    fontSize: typography.sizes.medium,
    fontWeight: "800",
    color: Colors.text,
    marginBottom: 2,
  },
  addressText: {
    fontSize: typography.sizes.medium,
    color: Colors.textSecondary,
  },
  gpsVerifiedBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.successLight,
    padding: 14,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: Colors.successLight,
    marginBottom: 16,
  },
  gpsVerifiedTitle: {
    fontSize: typography.sizes.medium,
    fontWeight: "700",
    color: Colors.success,
  },
  gpsVerifiedDesc: {
    fontSize: typography.sizes.small,
    color: Colors.success,
    marginTop: 1,
  },
  waitNotification: {
    backgroundColor: Colors.surfaceContainer,
    padding: 14,
    borderRadius: moderateScale(12),
    marginBottom: 16,
  },
  waitNotifyText: {
    fontSize: typography.sizes.medium,
    color: Colors.textSecondary,
    lineHeight: typography.lineHeights.medium,
    textAlign: "center",
  },

  timersGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  timerBlock: {
    backgroundColor: Colors.surfaceContainerLow,
    width: "48%",
    padding: 10,
    borderRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
  },
  timerBlockLabel: {
    fontSize: typography.sizes.small,
    fontWeight: "700",
    color: Colors.textSecondary,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  timerBlockVal: {
    fontSize: typography.sizes.large,
    fontWeight: "800",
    color: Colors.text,
  },
  checklistScroll: {
    marginBottom: 12,
  },
  checklistHeader: {
    fontSize: typography.sizes.small,
    fontWeight: "700",
    color: Colors.textMuted,
    letterSpacing: 0.8,
    marginTop: 6,
    marginBottom: 8,
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceContainer,
    gap: 10,
  },
  checkText: {
    fontSize: typography.sizes.medium,
    color: Colors.text,
    fontWeight: "600",
    flex: 1,
  },
  checkTextSelected: {
    textDecorationLine: "line-through",
    color: Colors.textMuted,
  },
  otpSection: {
    backgroundColor: Colors.surfaceContainerLow,
    padding: 12,
    borderRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: Colors.border,
    marginTop: 12,
    marginBottom: 6,
  },
  otpLabel: {
    fontSize: typography.sizes.small,
    fontWeight: "700",
    color: Colors.textSecondary,
    marginBottom: 6,
  },
  otpInput: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: moderateScale(8),
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: typography.sizes.medium,
    fontWeight: "700",
    color: Colors.text,
  },

  otpInputError: {
    borderColor: Colors.error,
    backgroundColor: Colors.errorLight,
  },
  errorText: {
    color: Colors.error,
    fontSize: typography.sizes.small,
    fontWeight: "600",
    marginTop: 4,
  },
  pickupActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  issueBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.errorLight,
    borderWidth: 1,
    borderColor: Colors.errorLight,
    borderRadius: moderateScale(12),
    paddingHorizontal: 16,
    width: "28%",
    gap: 4,
  },
  issueBtnText: {
    color: Colors.error,
    fontWeight: "700",
    fontSize: typography.sizes.medium,
  },
  pickupConfirmBtn: {
    flex: 1,
    backgroundColor: Colors.brand,
    paddingVertical: 14,
    borderRadius: moderateScale(12),
    alignItems: "center",
  },
  customerRowInside: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surfaceContainerLow,
    padding: 12,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 16,
    gap: 12,
  },
  customerAvatarInside: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: Colors.brandSkin,
    alignItems: "center",
    justifyContent: "center",
  },
  customerInitialsInside: {
    fontSize: typography.sizes.large,
    fontWeight: "800",
    color: Colors.brand,
  },
  customerNameInside: {
    fontSize: typography.sizes.medium,
    fontWeight: "800",
    color: Colors.text,
  },
  customerPhoneInside: {
    fontSize: typography.sizes.small,
    color: Colors.textSecondary,
    marginTop: 1,
  },

  communicationBtns: {
    flexDirection: "row",
    gap: 8,
  },
  rideContactActions: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  roundCommBtn: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: moderateScale(18),
    backgroundColor: Colors.brandSkin,
    alignItems: "center",
    justifyContent: "center",
  },
  commBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: moderateScale(8),
    backgroundColor: Colors.error,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  commBadgeText: {
    color: Colors.white,
    fontSize: typography.sizes.small,
    fontWeight: "800",
  },
  optionsBlock: {
    marginBottom: 14,
  },
  blockLabel: {
    fontSize: typography.sizes.small,
    fontWeight: "700",
    color: Colors.textMuted,
    marginBottom: 8,
  },
  optionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  optionBtn: {
    width: "31%",
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: moderateScale(8),
    alignItems: "center",
  },
  optionBtnSelected: {
    borderColor: Colors.brand,
    backgroundColor: Colors.brandSkin,
  },
  optionBtnText: {
    fontSize: typography.sizes.small,
    fontWeight: "700",
    color: Colors.textSecondary,
  },
  optionBtnTextSelected: {
    color: Colors.brand,
  },
  deliveredScroll: {
  },
  successHeader: {
    alignItems: "center",
    marginVertical: 12,
  },
  successTitle: {
    fontSize: typography.sizes.large,
    fontWeight: "800",
    color: Colors.text,
    marginTop: 6,
  },
  successSubtitle: {
    fontSize: typography.sizes.small,
    color: Colors.textSecondary,
    marginTop: 2,
    textAlign: "center",
  },
  earningsBreakdown: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 12,
    marginBottom: 14,
  },
  breakdownHeader: {
    fontSize: typography.sizes.small,
    fontWeight: "800",
    color: Colors.textSecondary,
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  breakdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  breakdownLabel: {
    fontSize: typography.sizes.medium,
    color: Colors.textSecondary,
  },
  breakdownVal: {
    fontSize: typography.sizes.medium,
    fontWeight: "700",
    color: Colors.text,
  },
  breakdownTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    marginTop: 10,
    paddingTop: 10,
  },
  breakdownTotalLabel: {
    fontSize: typography.sizes.medium,
    fontWeight: "800",
    color: Colors.text,
  },
  breakdownTotalVal: {
    fontSize: typography.sizes.large,
    fontWeight: "800",
    color: Colors.success,
  },

  feedbackSection: {
    backgroundColor: Colors.white,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 12,
    marginBottom: 14,
  },
  ratingStars: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 10,
  },
  feedbackInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: moderateScale(8),
    padding: 10,
    fontSize: typography.sizes.medium,
    height: moderateScale(60),
    color: Colors.text,
    textAlignVertical: "top",
  },
  heatmapZones: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 12,
    marginBottom: 8,
  },
  hotspotItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
  },
  hotspotText: {
    fontSize: typography.sizes.medium,
    fontWeight: "600",
    color: Colors.text,
  },
});
