import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";
import { moderateScale } from "react-native-size-matters";
import { fontFamilies } from "@/constants/typography";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  container: {
    flex: 1,
  },
  content: {
    padding: 16,
    gap: 16,
  },
  startRideBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: moderateScale(20),
  },
  startRideBtnText: {
    color: '#fff',
    fontFamily: 'Inter_600SemiBold',
    fontSize: moderateScale(14),
  },
  headerGradient: {
    borderBottomLeftRadius: moderateScale(24),
    borderBottomRightRadius: moderateScale(24),
    overflow: 'hidden',
    position: 'relative',
    paddingBottom: 40,
  },
  headerBgImage: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 140,
    opacity: 0.15,
  },
  headerContent: {
    paddingHorizontal: 20,
    paddingBottom: 57.5,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    zIndex: 2,
  },
  menuButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  greeting: {
    fontFamily: "Inter_700Bold",
    fontSize: moderateScale(20),
    color: '#fff',
  },
  subGreeting: {
    fontFamily: "Inter_500Medium",
    fontSize: moderateScale(13),
    color: 'rgba(255,255,255,0.9)',
    marginTop: 2,
  },
  heroIllustration: {
    position: 'absolute',
    right: 16,
    top: -85,
    width: 100,
    height: 100,
    zIndex: 10,
  },
  onlineBadgeHero: {
    position: 'absolute',
    right: 14,
    top: -96,
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: moderateScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    zIndex: 11,
  },
  onlineBadgeDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: Colors.success,
  },
  onlineBadgeText: {
    fontFamily: 'Inter_700Bold',
    fontSize: moderateScale(9),
    color: Colors.success,
  },
  statusCard: {
    backgroundColor: '#fff',
    borderRadius: moderateScale(16),
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    marginTop: 0,
    marginBottom: 0,
    zIndex: 5,
  },
  statusIconBg: {
    width: moderateScale(48),
    height: moderateScale(48),
    borderRadius: moderateScale(24),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  statusCardCopy: {
    flex: 1,
  },
  statusCardTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: moderateScale(15),
    color: Colors.text,
    marginBottom: 2,
  },
  statusCardDesc: {
    fontFamily: 'Inter_500Medium',
    fontSize: moderateScale(12),
    color: Colors.textMuted,
  },
  powerButton: {
    width: moderateScale(48),
    height: moderateScale(48),
    borderRadius: moderateScale(24),
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  powerButtonOnline: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  homeModeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.surface,
    borderRadius: moderateScale(14),
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  homeModeRowActive: {
    backgroundColor: Colors.brandSkin,
    borderColor: Colors.primary,
  },
  homeModeLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  homeModeIconWrap: {
    width: moderateScale(38),
    height: moderateScale(38),
    borderRadius: moderateScale(10),
    backgroundColor: Colors.brandSkin,
    alignItems: "center",
    justifyContent: "center",
  },
  homeModeIconWrapActive: {
    backgroundColor: Colors.primary,
  },
  homeModeTextWrap: {
    flex: 1,
  },
  homeModeLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: moderateScale(14),
    color: Colors.text,
    marginBottom: 2,
  },
  homeModeLabelActive: {
    color: Colors.primaryDark,
  },
  homeModeDesc: {
    fontFamily: "Inter_400Regular",
    fontSize: moderateScale(12),
    color: Colors.textMuted,
  },
  homeModeSwitch: {
    width: moderateScale(44),
    height: moderateScale(24),
    borderRadius: moderateScale(12),
    backgroundColor: Colors.border,
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  homeModeSwitchActive: {
    backgroundColor: Colors.primary,
  },
  homeModeSwitchThumb: {
    width: moderateScale(18),
    height: moderateScale(18),
    borderRadius: moderateScale(9),
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  homeModeSwitchThumbActive: {
    alignSelf: "flex-end",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    fontFamily: "Inter_700Bold",
    fontSize: moderateScale(15),
    color: Colors.text,
  },
  sectionSpacing: {
    marginTop: 4,
  },
  emptyTasksCard: {
    backgroundColor: Colors.surface,
    borderRadius: moderateScale(16),
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  emptyTasksImg: {
    width: 80,
    height: 80,
    marginRight: 16,
  },
  emptyTasksCopy: {
    flex: 1,
  },
  emptyTasksTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: moderateScale(15),
    color: Colors.text,
    marginBottom: 4,
  },
  emptyTasksDesc: {
    fontFamily: 'Inter_400Regular',
    fontSize: moderateScale(12),
    color: Colors.textSecondary,
    lineHeight: 18,
  },
  calendarBtn: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: Colors.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
  },
  safetyAlert: {
    flexDirection: "row",
    backgroundColor: Colors.warningLight,
    borderRadius: moderateScale(16),
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.warning + "40",
    gap: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  safetyContent: {
    flex: 1,
    marginRight: 60,
  },
  safetyTitle: {
    fontFamily: fontFamilies.body.bold,
    fontSize: moderateScale(15),
    color: Colors.warning,
    marginBottom: 4,
  },
  safetyText: {
    fontFamily: fontFamilies.body.medium,
    fontSize: moderateScale(12),
    color: Colors.warning,
    lineHeight: 18,
  },
  safetyImg: {
    width: 80,
    height: 80,
    position: 'absolute',
    right: -10,
    bottom: -10,
  },
  scheduledCard: {
    backgroundColor: Colors.surface,
    borderRadius: moderateScale(14),
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  scheduledHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: Colors.border,
    paddingBottom: 10,
    marginBottom: 10,
  },
  scheduledTime: {
    fontFamily: "Inter_600SemiBold",
    fontSize: moderateScale(14),
    color: Colors.text,
  },
  scheduledPrice: {
    fontFamily: "Inter_700Bold",
    fontSize: moderateScale(15),
    color: Colors.success,
  },
  scheduledBody: {
    gap: 8,
    marginBottom: 10,
  },
  addressLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  addressText: {
    fontFamily: "Inter_400Regular",
    fontSize: moderateScale(13),
    color: Colors.textSecondary,
    flex: 1,
  },
  connectorLine: {
    width: 1,
    height: 12,
    backgroundColor: Colors.border,
    marginLeft: 3.5,
    marginTop: -6,
    marginBottom: -6,
  },
  scheduledFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderColor: Colors.border,
    paddingTop: 10,
  },
  customerName: {
    fontFamily: "Inter_500Medium",
    fontSize: moderateScale(12),
    color: Colors.textMuted,
  },
  badge: {
    backgroundColor: Colors.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: moderateScale(6),
  },
  badgeText: {
    fontFamily: "Inter_700Bold",
    fontSize: moderateScale(10),
    color: Colors.primaryDark,
  },
});
