import { StyleSheet, Dimensions } from "react-native";
import { type ServiceTokens, type ThemeTokens } from "@/constants/colors";
import { typography } from "@/constants/typography";
const { height } = Dimensions.get("window");

// Part of the pickup-confirmation.styles stylesheet, kept under the 150-line file limit.
// Values are unchanged; pickup-confirmation.styles.ts composes this back together.

export const createMapAreaStyles = (tokens: ThemeTokens, accent: ServiceTokens, insets: any) =>
  StyleSheet.create({
    mapArea: {
      height: height * 0.64,
      backgroundColor: "#eef1f4",
    },
    backButton: {
      position: "absolute",
      left: 16,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: tokens.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    locateButton: {
      position: "absolute",
      right: 16,
      bottom: 18,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: tokens.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    centerMarker: {
      position: "absolute",
      left: "50%",
      top: "50%",
      marginLeft: -75,
      marginTop: -58,
      width: 150,
      height: 92,
      alignItems: "center",
      justifyContent: "flex-start",
      zIndex: 8,
      elevation: 8,
    },
    markerWrap: {
      alignItems: "center",
      width: 150,
      height: 92,
    },
    pickupBubble: {
      backgroundColor: accent.accent,
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 18,
      marginBottom: 6,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      minWidth: 116,
      alignItems: "center",
    },
    pickupBubbleText: {
      color: accent.on,
      fontSize: typography.sizes.medium,
      fontWeight: "800",
    },
    pin: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: accent.accent,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: tokens.surface,
    },
    panel: {
      flex: 1,
      marginTop: -18,
      backgroundColor: tokens.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: insets.bottom > 0 ? insets.bottom + 22 : 34,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -6 },
      shadowOpacity: 0.08,
      shadowRadius: 14,
      elevation: 16,
    },
    handle: {
      width: 38,
      height: 4,
      borderRadius: 2,
      backgroundColor: tokens.border,
      alignSelf: "center",
      marginBottom: 14,
    },
  });
