import { Dimensions, StyleSheet } from "react-native";
import { type ServiceTokens, type ThemeTokens } from "@/constants/colors";

// Styles for app/pickup-confirmation.tsx. Moved out of the screen unchanged -- every value
// is exactly as it was, so nothing renders differently. Lives here rather
// than beside the screen because app/ is Expo Router's routing directory
// and a non-route file in there is treated as a route.

const { height } = Dimensions.get("window");

export const createStyles = (tokens: ThemeTokens, accent: ServiceTokens, insets: any) =>
  StyleSheet.create({
    mapArea: {
      height: height * 0.64,
      backgroundColor: "#eef1f4",
    },
    backButton: {
      position: "absolute",
      left: 16,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: tokens.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    locateButton: {
      position: "absolute",
      right: 16,
      bottom: 18,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: tokens.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    centerMarker: {
      position: "absolute",
      left: "50%",
      top: "50%",
      marginLeft: -75,
      marginTop: -58,
      width: 150,
      height: 92,
      alignItems: "center",
      justifyContent: "flex-start",
      zIndex: 8,
      elevation: 8,
    },
    markerWrap: {
      alignItems: "center",
      width: 150,
      height: 92,
    },
    pickupBubble: {
      backgroundColor: accent.accent,
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 18,
      marginBottom: 6,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      minWidth: 116,
      alignItems: "center",
    },
    pickupBubbleText: {
      color: accent.on,
      fontSize: 13,
      fontWeight: "800",
    },
    pin: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: accent.accent,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: tokens.surface,
    },
    panel: {
      flex: 1,
      marginTop: -18,
      backgroundColor: tokens.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: insets.bottom > 0 ? insets.bottom + 22 : 34,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -6 },
      shadowOpacity: 0.08,
      shadowRadius: 14,
      elevation: 16,
    },
    handle: {
      width: 38,
      height: 4,
      borderRadius: 2,
      backgroundColor: tokens.border,
      alignSelf: "center",
      marginBottom: 14,
    },
    title: {
      fontSize: 16,
      fontWeight: "800",
      color: tokens.text,
      marginBottom: 18,
    },
    addressCard: {
      borderWidth: 2,
      borderColor: accent.accent,
      borderRadius: 10,
      backgroundColor: tokens.sunken,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginBottom: 12,
    },
    addressTitle: {
      fontSize: 16,
      fontWeight: "800",
      color: tokens.text,
      marginBottom: 1,
    },
    addressSubtitle: {
      fontSize: 13,
      color: tokens.sec,
    },
    metaRow: {
      minHeight: 28,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 26,
    },
    metaText: {
      fontSize: 13,
      fontWeight: "700",
      color: tokens.sec,
    },
    metaValue: {
      minWidth: 62,
      alignItems: "flex-end",
    },
    updateButton: {
      height: 46,
      borderRadius: 23,
      backgroundColor: accent.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    updateButtonText: {
      color: accent.on,
      fontSize: 15,
      fontWeight: "800",
    },
  });
