import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

// Part of the ride-searching.styles stylesheet, kept under the 150-line file limit.
// Values are unchanged; ride-searching.styles.ts composes this back together.

export const createRootStyles = (colors: typeof Colors.light, insets: any) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    mapArea: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "#eef1f4",
    },
    screenBackButton: {
      position: "absolute",
      top: insets.top + 12,
      left: 16,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 8,
      elevation: 8,
      zIndex: 8,
    },
    pickupMarkerWrap: {
      alignItems: "center",
    },
    pickupMarker: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.success,
      borderWidth: 3,
      borderColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    pickupDot: {
      width: 9,
      height: 9,
      borderRadius: 4.5,
      backgroundColor: colors.surface,
    },
    pickupStem: {
      width: 3,
      height: 24,
      backgroundColor: colors.textSecondary,
      marginTop: -1,
    },
    dropMarker: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.error,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    driverMarker: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    dropMarkerInner: {
      width: 9,
      height: 9,
      borderRadius: 4.5,
      backgroundColor: colors.surface,
    },
    panel: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingBottom: insets.bottom > 0 ? insets.bottom + 12 : 24,
      justifyContent: "flex-end",
    },
  });
