import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

// Styles for app/ride-searching.tsx. Moved out of the screen unchanged --
// every value is exactly as it was, so nothing renders differently. Lives
// here rather than beside the screen because app/ is Expo Router's routing
// directory and a non-route file in there is treated as a route.

export const createStyles = (colors: typeof Colors.light, insets: any) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    mapArea: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "#eef1f4",
    },
    screenBackButton: {
      position: "absolute",
      top: insets.top + 12,
      left: 16,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 8,
      elevation: 8,
      zIndex: 8,
    },
    pickupMarkerWrap: {
      alignItems: "center",
    },
    pickupMarker: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.success,
      borderWidth: 3,
      borderColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    pickupDot: {
      width: 9,
      height: 9,
      borderRadius: 4.5,
      backgroundColor: colors.surface,
    },
    pickupStem: {
      width: 3,
      height: 24,
      backgroundColor: colors.textSecondary,
      marginTop: -1,
    },
    dropMarker: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.error,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    driverMarker: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    dropMarkerInner: {
      width: 9,
      height: 9,
      borderRadius: 4.5,
      backgroundColor: colors.surface,
    },
    panel: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingBottom: insets.bottom > 0 ? insets.bottom + 12 : 24,
      justifyContent: "flex-end",
    },
    floatingCard: {
      borderRadius: 24,
      borderWidth: 1,
      padding: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
      gap: 16,
    },
    handle: {
      width: 42,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: "center",
      marginBottom: 11,
    },
    headerInfo: {
      marginBottom: 16,
    },
    statusDotRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 4,
    },
    pulseDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginRight: 8,
    },
    title: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.text,
    },
    subtitle: {
      fontSize: 13,
      color: colors.textSecondary,
      marginLeft: 16, // aligns with title text indent
    },
    progressTrack: {
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.borderLight,
      overflow: "hidden",
      position: "relative",
      marginBottom: 20,
    },
    progressBarActive: {
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
      width: 120,
      backgroundColor: colors.primary,
      borderRadius: 2,
    },
    fareCard: {
      height: 64,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    bikeBadge: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    fareTextGroup: {
      flex: 1,
    },
    fareLabel: {
      fontSize: 14,
      color: colors.text,
      marginBottom: 3,
    },
    fareValue: {
      fontSize: 14,
      color: colors.text,
      fontWeight: "800",
    },
    tripButton: {
      height: 34,
      paddingHorizontal: 18,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    tripButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    dashedLine: {
      borderTopWidth: 1,
      borderStyle: "dashed",
      borderColor: colors.border,
      marginHorizontal: -16,
      marginBottom: 12,
    },
    suggestionCard: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      borderRadius: 14,
      paddingHorizontal: 18,
      paddingTop: 13,
      paddingBottom: 14,
    },
    suggestionHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 13,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
      overflow: "hidden",
    },
    suggestionTitle: {
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "800",
      color: colors.text,
    },
    addFareRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
    },
    addFarePill: {
      minWidth: 62,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    addFareText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
    },
    bookAgainOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 45,
      justifyContent: "flex-end",
    },
    bookAgainBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
    },
    bookAgainBackFloating: {
      position: "absolute",
      left: 18,
      bottom: 600,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
    bookAgainSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 18,
      paddingTop: 32,
      paddingBottom: insets.bottom > 0 ? insets.bottom + 34 : 58,
    },
    bookAgainTitle: {
      fontSize: 16,
      lineHeight: 22,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 10,
    },
    serviceSummaryCard: {
      height: 52,
      borderRadius: 10,
      backgroundColor: colors.surfaceSecondary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    serviceLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    serviceBikeBadge: {
      width: 42,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    serviceName: {
      fontSize: 14,
      fontWeight: "900",
      color: colors.text,
    },
    serviceFare: {
      fontSize: 14,
      fontWeight: "900",
      color: colors.text,
    },
    bookDashedLine: {
      borderTopWidth: 1,
      borderStyle: "dashed",
      borderColor: colors.border,
      marginBottom: 10,
    },
    locationTitle: {
      fontSize: 16,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 9,
    },
    locationRows: {
      flexDirection: "row",
      paddingBottom: 10,
    },
    locationRail: {
      width: 24,
      alignItems: "center",
      paddingTop: 3,
      marginRight: 8,
    },
    pickupSmallDot: {
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.success,
      borderWidth: 4,
      borderColor: colors.surface,
    },
    locationDashes: {
      width: 1,
      height: 35,
      borderLeftWidth: 1,
      borderStyle: "dashed",
      borderColor: colors.border,
      marginVertical: 2,
    },
    dropSmallDot: {
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.error,
      borderWidth: 4,
      borderColor: colors.surface,
    },
    locationTextColumn: {
      flex: 1,
    },
    locationRow: {
      minHeight: 51,
    },
    locationName: {
      fontSize: 14,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 2,
    },
    locationAddress: {
      fontSize: 12,
      lineHeight: 16,
      color: colors.textSecondary,
    },
    totalFareRow: {
      height: 44,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginHorizontal: -18,
      paddingHorizontal: 18,
      marginBottom: 0,
    },
    totalFareLabel: {
      fontSize: 16,
      fontWeight: "900",
      color: colors.text,
    },
    totalFareValue: {
      fontSize: 16,
      fontWeight: "900",
      color: colors.text,
    },
    paymentRow: {
      height: 46,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: -18,
      paddingHorizontal: 18,
      borderBottomWidth: 1,
      borderColor: colors.border,
      marginBottom: 22,
    },
    paymentText: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    backYellowButton: {
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    backYellowText: {
      fontSize: 15,
      fontWeight: "800",
      color: colors.surface,
    },
    cancelRideButton: {
      height: 46,
      borderRadius: 23,
      borderWidth: 1,
      borderColor: colors.error,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    cancelRideText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.error,
    },
    cancelFlowOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 70,
      justifyContent: "flex-end",
    },
    cancelFlowBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
    },
    cancelFlowBackButton: {
      position: "absolute",
      left: 14,
      bottom: 562,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.18,
      shadowRadius: 7,
      elevation: 8,
    },
    cancelReasonSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: insets.bottom > 0 ? insets.bottom + 22 : 28,
      minHeight: 520,
    },
    cancelSheetHandle: {
      width: 48,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: "center",
      marginBottom: 22,
    },
    cancelReasonTitle: {
      fontSize: 18,
      lineHeight: 22,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 6,
    },
    cancelReasonSubtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
      marginBottom: 10,
    },
    cancelReasonDivider: {
      borderTopWidth: 1,
      borderStyle: "dashed",
      borderColor: colors.border,
      marginBottom: 14,
    },
    cancelReasonRow: {
      height: 54,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 14,
    },
    cancelReasonText: {
      flex: 1,
      fontSize: 14,
      lineHeight: 19,
      fontWeight: "800",
      color: colors.text,
      paddingRight: 10,
    },
    cancelConfirmClose: {
      position: "absolute",
      right: 16,
      bottom: 476,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.18,
      shadowRadius: 7,
      elevation: 8,
      zIndex: 75,
    },
    cancelConfirmSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: insets.bottom > 0 ? insets.bottom + 22 : 34,
      minHeight: 462,
    },
    cancelConfirmTitle: {
      fontSize: 20,
      lineHeight: 24,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 12,
    },
    cancelConfirmCopy: {
      fontSize: 15,
      lineHeight: 20,
      color: colors.textSecondary,
      marginBottom: 18,
    },
    selectedReasonBox: {
      backgroundColor: colors.surfaceSecondary,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      marginBottom: 18,
    },
    selectedReasonLabel: {
      fontSize: 12,
      lineHeight: 16,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    selectedReasonText: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "800",
      color: colors.text,
    },
    currentAddressLabel: {
      fontSize: 15,
      lineHeight: 20,
      color: colors.text,
      marginBottom: 10,
    },
    cancelAddressRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 24,
    },
    cancelAddressDot: {
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.success,
      borderWidth: 4,
      borderColor: colors.surface,
      marginHorizontal: 6,
      marginRight: 18,
    },
    cancelAddressTextGroup: {
      flex: 1,
    },
    cancelAddressTitle: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "900",
      color: colors.text,
      marginBottom: 1,
    },
    cancelAddressDetail: {
      fontSize: 12,
      lineHeight: 16,
      color: colors.textSecondary,
    },
    cancelMyRideButton: {
      height: 46,
      borderRadius: 23,
      backgroundColor: colors.error,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 16,
    },
    cancelMyRideText: {
      fontSize: 14,
      fontWeight: "700",
      color: "#FFFFFF",
    },
    keepSearchingButton: {
      height: 46,
      borderRadius: 23,
      borderWidth: 1,
      borderColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    keepSearchingText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.primary,
    },
  });
