import { Platform, StyleSheet } from "react-native";
import { moderateScale } from "react-native-size-matters";
import { type ServiceTokens, type ThemeTokens } from "@/constants/colors";
import { fontFamilies } from "@/constants/typography";
import { CARD_GAP, CARD_W } from "./constants";

// Styles for app/(tabs)/index.tsx. Moved out of the screen unchanged -- every
// value is exactly as it was, so nothing renders differently. Lives here
// rather than beside the screen because app/ is Expo Router's routing
// directory and a non-route file in there is treated as a route.

export const createStyles = (tokens: ThemeTokens, accent: ServiceTokens) => StyleSheet.create({
  root: { flex: 1, backgroundColor: tokens.bg },
  mainScrollContent: { paddingBottom: 100 },

  topRow: {
    flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between",
    paddingHorizontal: 16, paddingTop: 6,
  },
  addressBlock: { flex: 1, minWidth: 0 },
  addressEyebrow: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 1, textTransform: "uppercase", color: accent.accent },
  addressLabelRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 5 },
  addressLabel: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(17), color: tokens.text },
  addressLine: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec, marginTop: 3 },
  topRowActions: { flexDirection: "row", gap: 10 },
  iconBtnCircle: {
    width: moderateScale(44), height: moderateScale(44), borderRadius: moderateScale(22),
    backgroundColor: tokens.sunken, borderWidth: 1, borderColor: tokens.border, alignItems: "center", justifyContent: "center",
  },
  avatarBtn: {
    width: moderateScale(44), height: moderateScale(44), borderRadius: moderateScale(22),
    backgroundColor: tokens.sunken, borderWidth: 1, borderColor: tokens.border, alignItems: "center", justifyContent: "center",
  },

  headline: {
    fontFamily: fontFamilies.heading.bold, fontSize: moderateScale(28), lineHeight: moderateScale(31),
    letterSpacing: -0.6, color: tokens.text, paddingHorizontal: 16, marginTop: 18,
  },

  searchBar: {
    flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: tokens.surface,
    borderWidth: 1, borderColor: accent.accent, borderRadius: moderateScale(14), height: moderateScale(48),
    paddingHorizontal: 14, marginHorizontal: 16, marginTop: 14,
  },
  searchPlaceholder: { flex: 1, fontFamily: fontFamilies.body.regular, fontSize: moderateScale(14), color: tokens.sec },

  tilesRow: { flexDirection: "row", gap: 10, paddingHorizontal: 16, marginTop: 16, alignItems: "stretch" },
  togglePill: { flex: 1, flexDirection: "row", gap: 4, backgroundColor: accent.skin, borderRadius: moderateScale(22), padding: 4 },
  toggleCell: { flex: 1, borderRadius: moderateScale(18), borderWidth: 1.5, borderColor: "transparent", paddingVertical: 9, alignItems: "center", gap: 7 },
  launcherTile: {
    flex: 1, backgroundColor: tokens.surface, borderWidth: 1, borderColor: tokens.border, borderRadius: moderateScale(20),
    paddingVertical: 10, alignItems: "center", gap: 7, position: "relative",
  },
  launcherArrow: { position: "absolute", top: 6, right: 8, fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), color: tokens.sec },
  toggleIconCircle: { width: moderateScale(32), height: moderateScale(32), borderRadius: moderateScale(11), alignItems: "center", justifyContent: "center" },
  toggleEmoji: { fontSize: moderateScale(15) },
  // Ride/Task carry a permanent skin tint, so the slack around a 15pt emoji in
  // the 32pt toggle circle showed up as an oversized empty box. Tighter frame,
  // bigger glyph — the icon fills ~63% of it instead of ~47%.
  launcherIconCircle: { width: moderateScale(30), height: moderateScale(30), borderRadius: moderateScale(10), alignItems: "center", justifyContent: "center" },
  launcherEmoji: { fontSize: moderateScale(19), lineHeight: moderateScale(23), textAlign: "center", includeFontPadding: false },
  toggleLabel: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(12), color: tokens.sec },

  promoSection: { marginTop: 20 },
  promoScrollContent: { paddingHorizontal: 16, gap: CARD_GAP },
  promoCard: { width: CARD_W, height: 140, borderRadius: moderateScale(18), borderWidth: 1, borderColor: tokens.border, padding: 18, justifyContent: "space-between" },
  promoEyebrow: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 1, textTransform: "uppercase" },
  promoHeadline: { fontFamily: fontFamilies.heading.bold, fontSize: moderateScale(24), lineHeight: moderateScale(26), letterSpacing: -0.5, color: tokens.text, marginTop: 8 },
  promoCaption: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec },
  promoDotsRow: { flexDirection: "row", justifyContent: "center", gap: 5, paddingTop: 12 },
  promoDot: { height: 5, borderRadius: 999 },

  adCard: { marginHorizontal: 16, marginTop: 16, borderRadius: moderateScale(16), overflow: "hidden", borderWidth: 1, borderColor: tokens.border },
  adImage: { width: "100%", height: 140 },
  adCaption: { padding: 12, backgroundColor: tokens.surface },
  adTitle: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(15), color: tokens.text },
  adDescription: { fontFamily: fontFamilies.body.regular, fontSize: moderateScale(12), color: tokens.sec, marginTop: 2 },

  sectionBlock: { marginTop: 24, paddingHorizontal: 16 },
  sectionHeadRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  sectionHeadLeft: { flexDirection: "row", alignItems: "baseline", gap: 8 },
  sectionTitle: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(17), letterSpacing: -0.1, color: tokens.text },
  sectionMeta: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec },
  sectionSeeAll: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 1, textTransform: "uppercase", color: accent.accent },
  mealsScrollContent: { gap: 12 },

  mealCard: { width: 132 },
  mealImageWrap: { position: "relative" },
  mealImage: { width: 132, height: 96, borderRadius: moderateScale(8), backgroundColor: tokens.sunken },
  mealPriceBadge: { position: "absolute", top: 6, left: 6, backgroundColor: accent.accent, borderRadius: moderateScale(5), paddingHorizontal: 6, paddingVertical: 3 },
  mealPriceBadgeText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(10), letterSpacing: 0.5, color: accent.on },
  mealAddBtn: {
    position: "absolute", bottom: -10, right: 6, width: moderateScale(26), height: moderateScale(26), borderRadius: moderateScale(13),
    backgroundColor: accent.accent, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: tokens.bg,
  },
  mealAddBtnText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(12), color: accent.on },
  mealName: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(14), color: tokens.text, marginTop: 8 },
  mealVendor: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec, marginTop: 2 },

  vegOnlyRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, marginTop: 22 },
  vegOnlyLeft: { flexDirection: "row", alignItems: "center", gap: 9 },
  vegOnlyIcon: { width: moderateScale(16), height: moderateScale(16), borderWidth: 1.5, borderColor: tokens.veg, borderRadius: moderateScale(3), alignItems: "center", justifyContent: "center" },
  vegOnlyDot: { width: moderateScale(7), height: moderateScale(7), borderRadius: moderateScale(3.5), backgroundColor: tokens.veg },
  vegOnlyLabel: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(15), color: tokens.text },
  vegSwitchTrack: { width: moderateScale(52), height: moderateScale(30), borderRadius: 999, backgroundColor: tokens.sunken, padding: 3, justifyContent: "center" },
  vegSwitchThumb: { width: moderateScale(24), height: moderateScale(24), borderRadius: 999, backgroundColor: tokens.surface },

  chipsScrollContent: { paddingHorizontal: 16, gap: 8, marginTop: 16 },
  chip: {
    flexDirection: "row", alignItems: "center", backgroundColor: tokens.surface, borderWidth: 1, borderColor: tokens.borderStrong,
    borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9,
  },
  chipActive: { backgroundColor: accent.accent, borderColor: accent.accent },
  chipText: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec },
  chipTextActive: { color: accent.on, fontFamily: fontFamilies.body.semibold },
  chipFilled: { backgroundColor: accent.accent, borderColor: accent.accent },
  chipFilledText: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(13), color: accent.on },
  chipBadge: { marginLeft: 6, minWidth: moderateScale(16), height: moderateScale(16), borderRadius: moderateScale(8), backgroundColor: accent.on, alignItems: "center", justifyContent: "center", paddingHorizontal: 3 },
  chipBadgeText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(10), color: accent.accent },
  chipVegDot: { width: moderateScale(8), height: moderateScale(8), borderRadius: moderateScale(4), backgroundColor: tokens.veg, marginRight: 6 },

  cuisineSection: { marginTop: 22 },
  cuisineLabel: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 1, textTransform: "uppercase", color: accent.accent, paddingHorizontal: 16, marginBottom: 12 },
  cuisineScrollContent: { paddingHorizontal: 16, gap: 16 },
  cuisineItem: { width: 64, alignItems: "center" },
  cuisineCircle: { width: 64, height: 64, borderRadius: 999, backgroundColor: tokens.sunken, borderWidth: 1, borderColor: tokens.border, alignItems: "center", justifyContent: "center" },
  cuisineEmoji: { fontSize: moderateScale(24) },
  cuisineName: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(12), color: tokens.text, marginTop: 7, textAlign: "center" },

  listHeadingBlock: { paddingHorizontal: 16, marginTop: 26, marginBottom: 12 },
  listHeading: { fontFamily: fontFamilies.heading.semibold, fontSize: moderateScale(22), letterSpacing: -0.3, color: tokens.text },
  listHeadingMeta: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec, marginTop: 2 },

  listSectionHeader: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 1.2, textTransform: "uppercase", color: accent.accent, paddingHorizontal: 16, paddingTop: 20, paddingBottom: 8 },

  stickyHeader: {
    position: "absolute", top: 0, left: 0, right: 0, zIndex: 100, backgroundColor: tokens.surface,
    borderBottomWidth: 1, borderBottomColor: tokens.border, paddingBottom: 10,
  },
  stickyRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16 },
  stickyAddress: { flex: 1, fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(15), color: tokens.text, marginRight: 8 },
  stickyActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  stickyTogglePill: { flexDirection: "row", gap: 3, backgroundColor: accent.skin, borderRadius: 999, padding: 3 },
  stickyToggleCell: { width: moderateScale(28), height: moderateScale(28), borderRadius: 999, alignItems: "center", justifyContent: "center" },
  stickyToggleEmoji: { fontSize: moderateScale(13) },
  stickyIconBtn: { width: moderateScale(30), height: moderateScale(30), borderRadius: 999, borderWidth: 1, borderColor: tokens.border, alignItems: "center", justifyContent: "center" },

  emptyIconCircle: {
    width: moderateScale(60), height: moderateScale(60), borderRadius: moderateScale(20),
    backgroundColor: tokens.sunken, alignItems: "center", justifyContent: "center",
  },

  emptySearchContainer: { alignItems: "center", justifyContent: "center", paddingTop: 40, paddingHorizontal: 28 },
  emptySearchTitle: { fontFamily: fontFamilies.heading.semibold, fontSize: moderateScale(20), letterSpacing: -0.3, color: tokens.text, marginTop: 18, textAlign: "center" },
  emptySearchSubtitle: { fontFamily: fontFamilies.body.regular, fontSize: moderateScale(14), lineHeight: moderateScale(20), color: tokens.sec, textAlign: "center", marginTop: 8 },
  tryInsteadLabel: {
    alignSelf: "flex-start", fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 1,
    textTransform: "uppercase", color: tokens.muted, marginTop: 20, marginBottom: 10,
  },
  tryInsteadRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tryInsteadChip: { borderWidth: 1, borderColor: tokens.borderStrong, backgroundColor: tokens.surface, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9 },
  tryInsteadChipText: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec },

  noServiceContainer: { flex: 1, alignItems: "center", justifyContent: "center", paddingVertical: 44, paddingHorizontal: 28 },
  noServiceTitle: { fontFamily: fontFamilies.heading.semibold, fontSize: moderateScale(20), letterSpacing: -0.3, color: tokens.text, marginTop: 18, textAlign: "center" },
  noServiceSubtitle: { fontFamily: fontFamilies.body.regular, fontSize: moderateScale(14), color: tokens.sec, textAlign: "center", marginTop: 8, lineHeight: moderateScale(20) },
  noServiceButton: { marginTop: 22, width: "100%", alignItems: "center", paddingVertical: 15, borderRadius: moderateScale(14), backgroundColor: accent.accent },
  noServiceButtonDisabled: { opacity: 0.6 },
  noServiceButtonText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(15), color: accent.on },
  noServiceSecondaryButton: { marginTop: 10, width: "100%", alignItems: "center", paddingVertical: 14, borderRadius: moderateScale(14), borderWidth: 1, borderColor: tokens.borderStrong, backgroundColor: tokens.surface },
  noServiceSecondaryButtonText: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(15), color: accent.accent },

  dishMenuItem: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 14, backgroundColor: tokens.surface, borderBottomWidth: 1, borderBottomColor: tokens.border },
  dishItemInfo: { flex: 1, paddingRight: 16 },
  dishItemTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  dishVegIndicator: { borderWidth: 1, width: moderateScale(14), height: moderateScale(14), alignItems: "center", justifyContent: "center", borderRadius: moderateScale(2) },
  dishVegDot: { width: moderateScale(6), height: moderateScale(6), borderRadius: moderateScale(3) },
  dishItemName: { flex: 1, fontFamily: fontFamilies.body.bold, fontSize: moderateScale(14), color: tokens.text },
  dishItemPrice: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(13), color: tokens.text, marginTop: 4 },
  dishItemDesc: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(11), color: tokens.sec, marginTop: 4, lineHeight: moderateScale(16) },
  dishVendorRow: { flexDirection: "row", alignItems: "center", marginTop: 8, gap: 4 },
  dishVendorText: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(11), color: tokens.sec },
  dishItemImageContainer: { width: 90, height: 90, position: "relative" },
  dishItemImage: { width: 90, height: 90, borderRadius: moderateScale(12), backgroundColor: tokens.sunken },
  dishAddButtonOverlay: { position: "absolute", bottom: -8, left: 8, right: 8, alignItems: "center" },
  dishAddPill: { backgroundColor: tokens.surface, borderWidth: 1, borderColor: tokens.borderStrong, paddingHorizontal: 16, paddingVertical: 5, borderRadius: moderateScale(8), minWidth: 70, alignItems: "center" },
  dishAddPillText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), color: accent.accent },
  dishSoldOutPill: { backgroundColor: tokens.sunken, borderWidth: 1, borderColor: tokens.border, paddingHorizontal: 16, paddingVertical: 5, borderRadius: moderateScale(8), minWidth: 70, alignItems: "center" },
  dishSoldOutPillText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), color: tokens.muted },
  dishQuantityPill: { flexDirection: "row", alignItems: "center", backgroundColor: tokens.surface, borderWidth: 1, borderColor: tokens.borderStrong, borderRadius: moderateScale(8), paddingHorizontal: 4, paddingVertical: 4, gap: 8 },
  dishQtyActionBtn: { paddingHorizontal: 4, paddingVertical: 2 },
  dishQtyText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), color: tokens.text },

  searchSheet: { backgroundColor: tokens.bg, borderBottomLeftRadius: moderateScale(24), borderBottomRightRadius: moderateScale(24), overflow: "hidden" },
  searchSheetHeaderRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 12, gap: 16 },
  searchSheetHeaderText: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(15), color: tokens.sec },
  searchSheetInputRow: { paddingHorizontal: 16, paddingBottom: 16 },
  searchSheetInputWrap: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: tokens.surface, borderWidth: 1, borderColor: accent.accent, borderRadius: moderateScale(14), paddingHorizontal: 14, paddingVertical: Platform.OS === "ios" ? 13 : 9 },
  searchSheetInput: { flex: 1, fontFamily: fontFamilies.body.medium, fontSize: moderateScale(15), color: tokens.text },
  searchSectionHeadRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  searchSectionTitle: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 1, color: tokens.muted },
  searchClearLink: { fontFamily: fontFamilies.body.semibold, fontSize: moderateScale(12), color: accent.accent },
  searchSuggestChip: { flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderColor: tokens.border, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  searchSuggestChipText: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec },

  distanceModalOverlay: { flex: 1, justifyContent: "flex-end" },
  distanceModalScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.5)" },
  distanceSheet: { backgroundColor: tokens.surface, borderTopLeftRadius: moderateScale(26), borderTopRightRadius: moderateScale(26), paddingHorizontal: 20, paddingTop: 10 },
  distanceSheetHandle: { width: moderateScale(42), height: moderateScale(4), borderRadius: moderateScale(2), backgroundColor: tokens.borderStrong, alignSelf: "center", marginBottom: 18 },
  distanceSheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 },
  distanceTitle: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(18), color: tokens.text },
  distanceSubtitle: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(12), color: tokens.sec, marginTop: 3 },
  distanceCloseBtn: { width: moderateScale(34), height: moderateScale(34), borderRadius: moderateScale(17), backgroundColor: tokens.sunken, alignItems: "center", justifyContent: "center" },
  distancePresetRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 14 },
  distanceChip: { minWidth: 68, alignItems: "center", justifyContent: "center", paddingHorizontal: 14, paddingVertical: 10, borderRadius: moderateScale(18), backgroundColor: tokens.sunken, borderWidth: 1, borderColor: tokens.border },
  distanceChipActive: { backgroundColor: accent.accent, borderColor: accent.accent },
  distanceChipText: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(13), color: tokens.text },
  distanceChipTextActive: { color: accent.on },
  distanceInputWrap: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: moderateScale(18), borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.sunken, paddingHorizontal: 14, marginBottom: 16 },
  distanceInput: { flex: 1, paddingVertical: Platform.OS === "ios" ? 14 : 10, color: tokens.text, fontFamily: fontFamilies.body.bold, fontSize: moderateScale(14) },
  distanceInputUnit: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(13), color: tokens.sec },
  distanceApplyBtn: { alignItems: "center", justifyContent: "center", paddingVertical: 15, borderRadius: moderateScale(18), backgroundColor: accent.accent },
  distanceApplyText: { fontFamily: fontFamilies.body.bold, color: accent.on, fontSize: moderateScale(14) },
  distanceClearBtn: { alignItems: "center", justifyContent: "center", paddingVertical: 13, marginTop: 10, borderRadius: moderateScale(18), borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.surface },
  distanceClearText: { fontFamily: fontFamilies.body.bold, color: tokens.sec, fontSize: moderateScale(13) },

  startupAdOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", justifyContent: "center", alignItems: "center", padding: 24 },
  startupAdCard: { width: "90%", maxWidth: 340, backgroundColor: tokens.surface, borderRadius: moderateScale(18), overflow: "hidden", position: "relative" },
  startupAdCloseBtn: { position: "absolute", top: 12, right: 12, zIndex: 10, backgroundColor: tokens.surface, padding: 6, borderRadius: 14 },
  startupAdImage: { width: "100%", height: 200 },
  startupAdTitle: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(18), color: tokens.text, marginBottom: 6 },
  startupAdDescription: { fontFamily: fontFamilies.body.regular, fontSize: moderateScale(13), color: tokens.sec, lineHeight: moderateScale(18) },
  startupAdBtn: { backgroundColor: accent.accent, paddingVertical: 12, borderRadius: moderateScale(12), alignItems: "center", marginTop: 16 },
  startupAdBtnText: { fontFamily: fontFamilies.body.bold, color: accent.on, fontSize: moderateScale(14) },

  filterModalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  filterModalScrim: { ...StyleSheet.absoluteFillObject },
  filterModalContent: { backgroundColor: tokens.surface, borderTopLeftRadius: moderateScale(24), borderTopRightRadius: moderateScale(24), height: "75%", overflow: "hidden" },
  filterModalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, borderBottomWidth: 1, borderBottomColor: tokens.border },
  filterModalTitle: { fontFamily: fontFamilies.heading.bold, fontSize: moderateScale(18), color: tokens.text },
  filterModalCloseBtn: { padding: 4 },
  filterModalBody: { flex: 1, flexDirection: "row" },
  filterModalLeftPane: { width: "35%", backgroundColor: tokens.sunken, borderRightWidth: 1, borderRightColor: tokens.border },
  filterModalRightPane: { width: "65%", backgroundColor: tokens.surface },
  filterTabButton: { paddingVertical: 16, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: tokens.border, position: "relative" },
  filterTabButtonActive: { backgroundColor: tokens.surface },
  filterTabText: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.sec },
  filterTabTextActive: { color: accent.accent, fontFamily: fontFamilies.body.bold },
  filterTabIndicator: { position: "absolute", left: 0, top: 12, bottom: 12, width: 4, backgroundColor: accent.accent, borderTopRightRadius: 2, borderBottomRightRadius: 2 },
  filterSectionTitle: { fontFamily: fontFamilies.body.bold, fontSize: moderateScale(11), letterSpacing: 0.8, color: tokens.muted, marginBottom: 16 },
  filterOptionRow: { flexDirection: "row", alignItems: "center", paddingVertical: 12, gap: 12 },
  filterOptionLabel: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(14), color: tokens.sec },
  filterEmptyNote: { fontFamily: fontFamilies.body.medium, fontSize: moderateScale(13), color: tokens.muted, fontStyle: "italic", marginTop: 10 },
  filterModalFooter: { flexDirection: "row", padding: 16, borderTopWidth: 1, borderTopColor: tokens.border, justifyContent: "space-between", alignItems: "center", backgroundColor: tokens.surface },
  filterModalClearBtn: { paddingVertical: 12, paddingHorizontal: 16 },
  filterModalClearText: { fontFamily: fontFamilies.body.bold, color: tokens.sec, fontSize: moderateScale(14) },
  filterModalApplyBtn: { backgroundColor: accent.accent, paddingVertical: 12, paddingHorizontal: 24, borderRadius: 999 },
  filterModalApplyText: { fontFamily: fontFamilies.body.bold, color: accent.on, fontSize: moderateScale(14) },
});
